# Generated by Django 5.1.1 on 2024-09-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_registro',
        ),
    ]
