# Generated by Django 5.1.1 on 2024-09-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuarios_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('usuarios_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
    ]
