# Generated by Django 5.1.1 on 2024-09-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_genero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='usuarios_id',
            new_name='genero_id',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='nombre_completo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='correo_electronico',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='generos',
        ),
    ]
